$(document).ready(function(){
	/*举报页面进入提问页面*/
	$(".js-report-list").click(function(){
		$(this).toggleClass("active");
		$(this).find('i').toggle();
	})
	//提交信息提示框
	$("#report-submit").click(function(){
		if($('.active').length<=0){
			mui.toast("请选择");
			return;
		}
		if($("textarea").val()==""){
			mui.toast("请填写补充说明");
		}else{
			//调取接口
			mui.toast("提交成功");
		}
	});
})

